[user]
  name = mike crockett
  useConfigOnly = true
  email = github@mmcrockett.com
[push]
  default = current
[core]
  excludesfile = ~/.gitignore
  autocrlf = input
  safecrlf = warn
  whitespace = tab-in-indent
[alias]
  hist     = log --graph --pretty=format:'%C(auto)%h %s %C(Cyan)%an %C(green)%ar %C(auto)%d' -n 20
  hist-all = log --graph --pretty=format:'%C(auto)%h %s %C(Cyan)%an %C(green)%ar %C(auto)%d'
[diff]
  tool = gvimdiff
[difftool]
  prompt = false
[merge]
  tool = meld
