[user]
  name = Mike Crockett
  useConfigOnly = true
[push]
  default = simple
[core]
  excludesfile = ~/.gitignore
  autocrlf = input
  safecrlf = warn
  whitespace = tab-in-indent
[alias]
  hist    = log --graph --pretty=format:'%C(Yellow)%h%Creset %s %C(Cyan)%an%Creset %C(green)%ar'
  hist-20 = log --graph --pretty=format:'%C(Yellow)%h%Creset %s %C(Cyan)%an%Creset %C(green)%ar' -n 20
